server:
  port: 8080
  servlet:
    context-path: /user
spring:
  mail:
    host: smtp.163.com #邮件服务器地址
    username: duroon79@163.com
    password: PATUHLNZSQYARTYO
    default-encoding: UTF-8 #默认编码格式
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform:h2
    schema:classpath:schema.sql
user:
  mail:
    subject: "用户注册成功"
    content: "恭喜，用户注册成功"

