drop table user if EXISTS;
create table user(id bigint generated by default as identity,user_name varchar(40) not null,password varchar(200) not null,
					name varchar(50),age int(3),email varchar(50),is_deleted varchar(1));